#!/usr/bin/env python3
"""Render the acceptance scenario registry for contributors.

The corpus `tests/fixtures/acceptance/scenario-corpus.json` is the source of
truth; `docs/acceptance-scenarios.md` is its rendered view, regenerated by this
script and guarded against drift by `tests/ci/test_acceptance_scenarios.py`.

Besides the catalogue itself the document cross-references the closed `apply`
registry (`crates/unica-coder/src/domain/apply.rs`) and the `check` profiles so
that a contributor can see which operations no scenario exercises yet and
propose the missing developer task.

    python scripts/ci/render-acceptance-registry.py --write   # refresh the document
    python scripts/ci/render-acceptance-registry.py --check   # fail on drift
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS = REPO_ROOT / "tests/fixtures/acceptance/scenario-corpus.json"
APPLY_REGISTRY = REPO_ROOT / "crates/unica-coder/src/domain/apply.rs"
CHECK_PROFILES = REPO_ROOT / "crates/unica-coder/src/application/v13/check.rs"
DOCUMENT = REPO_ROOT / "docs/acceptance-scenarios.md"

CLASS_TITLES = {
    "ok": "результат",
    "task": "длинная задача",
    "provider": "провайдер недоступен",
    "refused": "умышленный типизированный отказ",
    "unsupported": "закрытый список",
    "cancelled": "задача отменена",
    "failed": "задача завершилась ошибкой",
    "gap": "задокументированный пробел",
}

FAMILY_TITLES = OrderedDict(
    [
        ("Metadata", "Метаданные: объекты и коллекции"),
        ("Properties", "Свойства"),
        ("Form", "Формы"),
        ("Role", "Роли и права"),
        ("Dcs", "Схемы компоновки данных"),
        ("Mxl", "Табличные документы"),
        ("Xdto", "Пакеты XDTO"),
        ("Subsystem", "Подсистемы"),
        ("Support", "Поддержка поставщика"),
        ("Code", "Код BSL"),
        ("Event", "События"),
    ]
)

ARGS_TITLES = {
    "Values": "`values`",
    "Items": "`items`",
    "Text": "`text`",
    "Target": "только `at`",
}


def load_corpus() -> dict:
    return json.loads(CORPUS.read_text(encoding="utf-8"))


def load_apply_registry() -> tuple[list[tuple[str, str, str, str]], set[str]]:
    """The closed `apply` registry as `(operation, family, applicability, args)`
    tuples plus the set of operations the registry marks as implemented."""
    source = APPLY_REGISTRY.read_text(encoding="utf-8")
    # The registry is one `operation_descriptors!(...)` invocation; the macro
    # definition above it carries the same tokens, so anchor on the call.
    table_start = source.index("\noperation_descriptors!(")
    table_end = source.index("\n);", table_start)
    table = source[table_start:table_end]
    entries = re.findall(
        r'\(\s*"([A-Za-z]+\.[A-Za-z]+)",\s*(\w+),\s*(\w+),\s*(\w+)\s*\)',
        table,
    )
    if not entries:
        raise RuntimeError("the apply registry table was not found in domain/apply.rs")
    implemented_start = source.index("const IMPLEMENTED_APPLY_OPERATIONS: &[&str] = &[")
    implemented_end = source.index("];", implemented_start)
    implemented = set(re.findall(r'"([A-Za-z]+\.[A-Za-z]+)"', source[implemented_start:implemented_end]))
    return entries, implemented


def load_check_validators() -> list[str]:
    source = CHECK_PROFILES.read_text(encoding="utf-8")
    start = source.index("const NATIVE_VALIDATORS: &[CheckValidator] = &[")
    end = source.index("];", start)
    names = re.findall(r"CheckValidator::(\w+)", source[start:end])
    validators = [name.lower() for name in names]
    # `meta` runs through the typed metadata validator, outside CheckValidator.
    validators.append("meta")
    return validators


def step_wire(step: dict) -> str:
    tool = step["tool"].replace("unica.", "")
    args = step["args"]
    parts = [f"`{tool}`"]
    ops = [op.get("op", "?") for op in (args.get("ops") or [])]
    if ops:
        parts.append(" ".join(f"`{op}`" for op in ops))
    if step.get("validators"):
        parts.append("валидаторы " + ", ".join(f"`{name}`" for name in step["validators"]))
    if args.get("dryRun"):
        parts.append("(превью)")
    return " ".join(parts)


def step_classes(step: dict) -> str:
    return " / ".join(f"`{name}`" for name in step["expect"])


def scenario_ops(scenario: dict) -> set[str]:
    ops = set()
    for step in scenario["wire"]:
        for op in step["args"].get("ops") or []:
            if op.get("op"):
                ops.add(op["op"])
    return ops


def scenario_validators(scenario: dict) -> set[str]:
    validators = set()
    for step in scenario["wire"]:
        if step["tool"] == "unica.check":
            validators.update(step.get("validators") or [])
    return validators


def render(corpus: dict, registry: list[tuple[str, str, str, str]], implemented: set[str], profiles: list[str]) -> str:
    scenarios = corpus["scenarios"]
    steps = [step for scenario in scenarios for step in scenario["wire"]]
    class_counts: dict[str, int] = {}
    for step in steps:
        key = " / ".join(step["expect"])
        class_counts[key] = class_counts.get(key, 0) + 1
    gaps = [scenario["id"] for scenario in scenarios if any("gap" in step["expect"] for step in scenario["wire"])]

    op_scenarios: dict[str, list[str]] = {}
    for scenario in scenarios:
        for op in scenario_ops(scenario):
            op_scenarios.setdefault(op, []).append(scenario["id"])
    profile_scenarios: dict[str, list[str]] = {}
    for scenario in scenarios:
        for profile in scenario_validators(scenario):
            profile_scenarios.setdefault(profile, []).append(scenario["id"])
    tool_scenarios: dict[str, list[str]] = {}
    for scenario in scenarios:
        for tool in {step["tool"] for step in scenario["wire"]}:
            tool_scenarios.setdefault(tool, []).append(scenario["id"])

    uncovered = [op for op, _, _, _ in registry if op not in op_scenarios]
    not_implemented = [op for op, _, _, _ in registry if op not in implemented]

    lines: list[str] = []
    out = lines.append
    out("# Реестр приёмочных сценариев поверхности v0.13")
    out("")
    out("<!-- Сгенерировано scripts/ci/render-acceptance-registry.py из")
    out("     tests/fixtures/acceptance/scenario-corpus.json. Не правьте вручную:")
    out("     измените корпус и выполните `python scripts/ci/render-acceptance-registry.py --write`. -->")
    out("")
    out(
        f"Корпус держит **{len(scenarios)} сценариев** реальных задач разработчика конфигурации "
        f"и **{len(steps)} шагов** канонических вызовов `unica.*`. Каждый шаг заморожен в одном из "
        "классов ответа, и приёмочный тест `tests/ci/test_acceptance_scenarios.py` исполняет весь "
        "корпус против собранного `target/debug/unica` на рабочем пространстве "
        "`tests/fixtures/acceptance/workspace/`; сценарии форматных проб (выгрузка 2.21, без версии, "
        "без файла поддержки) идут на выведенном из него пространстве "
        "`tests/fixtures/acceptance/workspace-format/`, а сценарии ответа до допуска наборов — на пустом "
        "`tests/fixtures/acceptance/workspace-bare/`. Источник истины — JSON корпуса; этот документ — его "
        "рендер для людей, и проверка на расхождение входит в тот же тест."
    )
    out("")
    out("Словарь `run` и жизненный цикл задач в этот корпус не входят: у них будет собственный корпус.")
    out("")
    out("## Классы ответа шага")
    out("")
    out("| Класс | Что означает | Шагов |")
    out("| --- | --- | ---: |")
    for key in sorted(class_counts, key=lambda item: (-class_counts[item], item)):
        names = key.split(" / ")
        meaning = "; ".join(CLASS_TITLES.get(name, name) for name in names)
        if len(names) > 1:
            meaning = "любой из: " + meaning
        out(f"| {' / '.join(f'`{name}`' for name in names)} | {meaning} | {class_counts[key]} |")
    out("")
    out(
        "Провод проходной, когда каждый его шаг отвечает результатом или типизированным отказом своего "
        "класса. Сырой транспортный сбой и незадокументированный типизированный отказ роняют прогон. "
        f"Задокументированных пробелов (`gap`) сейчас: **{len(gaps)}**"
        + (f" ({', '.join(gaps)})." if gaps else ".")
    )
    out("")
    out("## Как предложить сценарий или операцию")
    out("")
    out(
        "Идеи новых задач приветствуются именно здесь: если в таблице покрытия ниже операция помечена "
        "как непокрытая, или вы видите задачу разработчика, которую поверхность должна решать одним "
        "проводом, а сценария нет, — это и есть предложение."
    )
    out("")
    out("1. Откройте issue по форме [«Новая операция»](https://github.com/IngvarConsulting/unica/issues/new?template=new_operation.yml) ")
    out("   (она сама ставит метку `area:surface`): задача словами разработчика 1С и, если можете, провод ")
    out("   вызовов, которым её должно быть можно решить. Этого достаточно: сценарий допишем вместе.")
    out("2. Или добавьте сценарий сами: следующий свободный номер `S###`, область из списка ниже, задача ")
    out("   одной фразой и провод шагов. Шаг — это `tool`, `args` и `expect`:")
    out("")
    out("   ```json")
    out("   {")
    out('     "id": "S267",')
    out('     "area": "Реквизиты и состав",')
    out('     "task": "Сделать реквизит обязательным для заполнения",')
    out('     "wire": [')
    out("       {")
    out('         "tool": "unica.apply",')
    out('         "args": {')
    out('           "at": "main:Catalog.Валюты.TabularSection.Представления.Attribute.КодЯзыка",')
    out('           "ops": [{"op": "attribute.set", "args": {"values": {"required": true}}}],')
    out('           "dryRun": true')
    out("         },")
    out('         "expect": ["ok"]')
    out("       }")
    out("     ]")
    out("   }")
    out("   ```")
    out("")
    out("3. Поднимите счётчики сценариев и шагов в тесте формы (`test_corpus_holds_the_run_free_scenario_set_uniquely_numbered`), ")
    out("   прогоните `python -m unittest tests/ci/test_acceptance_scenarios.py` и заморозьте тот класс, ")
    out("   которым поверхность действительно ответила. Умышленный отказ фиксируется с полем `refusal` — ")
    out("   точным текстом `код: сообщение` ответа; шаг `check` с профилем — с полем `status` (`passed` или ")
    out("   `failed`); пробел — с полем `gap` (причина); пробелов допускается не больше восьми, и каждый — ")
    out("   заявка на починку поверхности, а не на переутверждение корпуса.")
    out("4. Обновите этот документ: `python scripts/ci/render-acceptance-registry.py --write`.")
    out("")
    out("Адреса и аргументы в примере — реальные узлы фикстурного пространства; его состав описан в ")
    out("`tests/fixtures/acceptance/README.md`.")
    out("")
    out("## Покрытие реестра `apply`")
    out("")
    out(
        f"Закрытый реестр держит **{len(registry)} операций**; сценарии покрывают "
        f"**{len(registry) - len(uncovered)}**, помечены реализованными **{len(registry) - len(not_implemented)}**. "
        "Операция без сценария — первая кандидатура для новой задачи."
    )
    out("")
    families: dict[str, list[tuple[str, str, str, str]]] = OrderedDict()
    for entry in registry:
        families.setdefault(entry[1], []).append(entry)
    for family, entries in families.items():
        out(f"### {FAMILY_TITLES.get(family, family)}")
        out("")
        out("| Операция | Аргументы | Реализована | Сценарии |")
        out("| --- | --- | --- | --- |")
        for op, _, _, args in entries:
            ids = op_scenarios.get(op, [])
            covered = ", ".join(ids) if ids else "**не покрыто — предложите задачу**"
            out(
                f"| `{op}` | {ARGS_TITLES.get(args, f'`{args}`')} | "
                f"{'да' if op in implemented else 'нет'} | {covered} |"
            )
        out("")
    out("## Покрытие профилей `check`")
    out("")
    out("| Профиль | Сценарии |")
    out("| --- | --- |")
    for profile in profiles:
        ids = profile_scenarios.get(profile, [])
        out(f"| `{profile}` | {', '.join(ids) if ids else '**не покрыто — предложите задачу**'} |")
    out("")
    out("## Инструменты в проводах")
    out("")
    out("| Инструмент | Сценариев |")
    out("| --- | ---: |")
    for tool in sorted(tool_scenarios, key=lambda name: (-len(tool_scenarios[name]), name)):
        out(f"| `{tool}` | {len(tool_scenarios[tool])} |")
    out("")
    out("## Каталог сценариев")
    out("")
    areas: dict[str, list[dict]] = OrderedDict()
    for scenario in scenarios:
        areas.setdefault(scenario["area"], []).append(scenario)
    out("Области: " + " · ".join(f"{name} ({len(items)})" for name, items in areas.items()))
    out("")
    for name, items in areas.items():
        out(f"### {name}")
        out("")
        out("| № | Задача | Провод | Классы шагов |")
        out("| --- | --- | --- | --- |")
        for scenario in items:
            wire = "<br>".join(step_wire(step) for step in scenario["wire"])
            classes = "<br>".join(step_classes(step) for step in scenario["wire"])
            task = scenario["task"].replace("|", "\\|")
            out(f"| {scenario['id']} | {task} | {wire} | {classes} |")
        out("")
    return "\n".join(line.rstrip() for line in lines).rstrip("\n") + "\n"


def render_document() -> str:
    registry, implemented = load_apply_registry()
    return render(load_corpus(), registry, implemented, load_check_validators())


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write docs/acceptance-scenarios.md")
    mode.add_argument("--check", action="store_true", help="exit 1 when the document is stale")
    args = parser.parse_args(argv)
    rendered = render_document()
    if args.write:
        DOCUMENT.write_text(rendered, encoding="utf-8")
        print(f"wrote {DOCUMENT.relative_to(REPO_ROOT)}")
        return 0
    if args.check:
        current = DOCUMENT.read_text(encoding="utf-8") if DOCUMENT.exists() else ""
        if current != rendered:
            print(
                f"{DOCUMENT.relative_to(REPO_ROOT)} is stale; run "
                "`python scripts/ci/render-acceptance-registry.py --write`",
                file=sys.stderr,
            )
            return 1
        print("acceptance registry is up to date")
        return 0
    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
